Add a way to pass custom ENV variables.
swashata/wp-webpack-script pull request #1134
Opened 2020-10-27 15:38 UTC by ajgagnon

This lets the user pass custom ENV variables to webpack's Define plugin. The variable must start with `WPACKIO_` to be included to prevent leaking sensitive env variables client-side. 😁

2020-10-29 10:38 UTC, swashata requested changes
Kindly make these changes. I think, in the client side code, we should use something like `console.log(process.env.WPACKIO_ENV)`. That's how [CRA does it](https://create-react-app.dev/docs/adding-custom-environment-variables/).

2020-10-29 10:38 UTC, swashata commented on packages/scripts/src/config/WebpackConfigHelper.ts
> +				this.customEnv[key] = JSON.stringify(process?.env?.[key]);
Correct me if I am wrong, but shouldn't this be

```ts
this.customEnv[`process.env.${key}`] = JSON.stringify(process?.env?.[key]);
```

2020-10-29 10:38 UTC, swashata commented on packages/scripts/__tests__/config/WebpackConfigHelper.spec.ts
> +			expect(JSON.parse(cwc.customEnv.WPACKIO_ENV)).toBe('test');
Once we change the key of customEnv, we need to update here too

```ts
expect(JSON.parse(cwc.customEnv['process.env.WPACKIO_ENV'])).toBe('test');
```

2020-12-09 16:43 UTC, ajgagnon commented
Sorry for the delay on this. I ended up breaking my wrist and getting surgery, so typing is a pain. Hopefully I should be able to contribute in a few weks.

2020-12-11 15:04 UTC, swashata commented
No worries at all. Take rest and get well soon 🙂

2021-04-26 13:14 UTC, swashata commented
This isn't needed anymore, since v6 has the functionality.

2021-04-26 13:14 UTC, closed without merging